# Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

"""
Test Scenario 1: Correct formatting for b=0, c=0
    - Input: a=2, b=0, c=0
    - Expected Output: "2x² = 0"
Explanation: In this case, both b and c are 0. Therefore, the output should be in the format "ax² = 0".

Test Scenario 2: Correct formatting for c=0 and b>0
    - Input: a=3, b=5, c=0
    - Expected Output: "3x² +5x = 0"
Explanation: With c=0 and b being positive, the formula should be presented in the format of "ax² +bx = 0".

Test Scenario 3: Correct formatting for b=0 and c>0
    - Input: a=4, b=0, c=3
    - Expected Output: "4x² +3 = 0"
Explanation: Here, b=0 and c is positive, therefore we expect the output to be "ax² +c = 0".

Test Scenario 4: Correct formatting for b<0 and c=0
    - Input: a=5, b=-1, c=0
    - Expected Output: "5x² -1x = 0"
Explanation: In this case, b is negative and c=0. The output should appear as "ax² -bx = 0".

Test Scenario 5: Correct formatting for b=0 and c<0
    - Input: a=6, b=0, c=-2
    - Expected Output: "6x² -2 = 0"
Explanation: Here b=0 and c is negative, which means the output should be "ax² -c = 0".

Test Scenario 6: All coefficients exist with b and c being positive
    - Input: a=7, b=2, c=4
    - Expected Output: "7x² +2x +4 = 0"
Explanation: For this scenario, all coefficients are provided and both b and c are positive. The output should be "ax² +bx +c = 0".

Test Scenario 7: All coefficients exist with both b and c negative
    - Input: a=8, b=-3, c=-5
    - Expected Output: "8x² -3x -5 = 0"
Explanation: All coefficients are provided with both b and c negative. The output should be "ax² -bx -c = 0".
"""
import pytest
from Quadratic_Equation import get_formula

def test_get_formula_b_c_zero():
  # Test Scenario 1: Correct formatting for b=0, c=0
  assert get_formula(2, 0, 0) == "2x² = 0"

def test_get_formula_c_zero_b_positive():
  # Test Scenario 2: Correct formatting for c=0 and b>0
  assert get_formula(3, 5, 0) == "3x² +5x = 0"

def test_get_formula_b_zero_c_positive():
  # Test Scenario 3: Correct formatting for b=0 and c>0
  assert get_formula(4, 0, 3) == "4x² +3 = 0"

def test_get_formula_c_zero_b_negative():
  # Test Scenario 4: Correct formatting for b<0 and c=0
  assert get_formula(5, -1, 0) == "5x² -1x = 0"

def test_get_formula_b_zero_c_negative():
  # Test Scenario 5: Correct formatting for b=0 and c<0
  assert get_formula(6, 0, -2) == "6x² -2 = 0"

def test_get_formula_all_coefficients_positive():
  # Test Scenario 6: All coefficients exist with b and c being positive
  assert get_formula(7, 2, 4) == "7x² +2x +4 = 0"

def test_get_formula_all_coefficients_negative():
  # Test Scenario 7: All coefficients exist with both b and c negative
  assert get_formula(8, -3, -5) == "8x² -3x -5 = 0"
